#
version: 2.1
orbs:
  codecov: codecov/codecov@3.1.1
jobs:
  build:
    docker:
      - image: circleci/node:14.17.0-browsers

    environment:
      JOBS: max # https://gist.github.com/ralphtheninja/f7c45bdee00784b41fed

    working_directory: ~/styls

    steps:
      - checkout
      - run: sudo npm i -g pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run test:coverage --runInBand --detectOpenHandles
      - codecov/upload
