name: Docs CI

on:
  push:
    paths:
      - 'docs/**'

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.6.0]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: latest
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Setup install
        run: pnpm install --frozen-lockfile
      - name: Setup Test
        run: pnpm run test
      - name: build docs
        run: pnpm run build:doc
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: push docs
        run: |
          cd docs/dist
          git config --global user.name "github-actions[bot]"
          git config --global user.email "zoy-l@outlook.com"
          git init
          git checkout -B gh-pages
          git add -A
          git commit -m 'docs: update docs'
          git push -f git@github.com:zoy-l/styil.git gh-pages
